"""nftables firewall/NAT management.

A single ruleset file is rendered each time we apply, so the firewall state
matches the current AP/LAN/WAN selection deterministically. The dashboard
listens on the management interface only.
"""

import os
from typing import Dict, List, Optional

from .. import paths
from ..utils import append_log, run, write_text


TABLE_NAME = "roguelink"
NFT_TEMPLATE = """#!/usr/sbin/nft -f
# Generated by RogueLink — do not edit manually.

table inet {table} {{
    chain forward {{
        type filter hook forward priority filter; policy drop;
        ct state established,related accept
{forward_rules}
    }}
    chain input {{
        type filter hook input priority filter; policy accept;
{input_rules}
    }}
}}

table ip {table}_nat {{
    chain postrouting {{
        type nat hook postrouting priority srcnat; policy accept;
{nat_rules}
    }}
}}
"""


def _forward_rule(in_iface: str, out_iface: str) -> str:
    return f"        iifname \"{in_iface}\" oifname \"{out_iface}\" accept"


def _nat_rule(out_iface: str) -> str:
    return f"        oifname \"{out_iface}\" masquerade"


def _input_rule_dashboard(mgmt_iface: str, port: int) -> List[str]:
    return [
        f"        iifname \"{mgmt_iface}\" tcp dport {port} accept",
    ]


def render_ruleset(
    wan_iface: Optional[str],
    ap_iface: Optional[str],
    lan_iface: Optional[str],
    mgmt_iface: Optional[str],
    api_port: int,
) -> str:
    forward_rules: List[str] = []
    nat_rules: List[str] = []
    input_rules: List[str] = []

    if wan_iface and ap_iface:
        forward_rules.append(_forward_rule(ap_iface, wan_iface))
    if wan_iface and lan_iface:
        forward_rules.append(_forward_rule(lan_iface, wan_iface))
    # Allow management <-> WAN to keep dashboard egress (e.g. for self-update).
    if wan_iface and mgmt_iface:
        forward_rules.append(_forward_rule(mgmt_iface, wan_iface))

    if wan_iface:
        nat_rules.append(_nat_rule(wan_iface))

    if mgmt_iface:
        input_rules.extend(_input_rule_dashboard(mgmt_iface, api_port))
    # Always allow loopback API access.
    input_rules.append("        iifname \"lo\" accept")

    return NFT_TEMPLATE.format(
        table=TABLE_NAME,
        forward_rules="\n".join(forward_rules) if forward_rules else "",
        input_rules="\n".join(input_rules) if input_rules else "",
        nat_rules="\n".join(nat_rules) if nat_rules else "",
    )


def enable_ip_forwarding() -> bool:
    return run("sysctl -w net.ipv4.ip_forward=1")[1] == 0


def apply(ruleset_text: str) -> Dict:
    write_text(paths.NFT_RULESET_PATH, ruleset_text, mode=0o600)
    enable_ip_forwarding()
    out, code = run(f"nft -f {paths.NFT_RULESET_PATH}")
    append_log(paths.FIREWALL_LOG, f"apply rc={code} :: {out}")
    return {"ok": code == 0, "output": out, "ruleset_path": paths.NFT_RULESET_PATH}


def flush() -> Dict:
    cmd = (
        f"nft list table inet {TABLE_NAME} >/dev/null 2>&1 && "
        f"nft delete table inet {TABLE_NAME}; "
        f"nft list table ip {TABLE_NAME}_nat >/dev/null 2>&1 && "
        f"nft delete table ip {TABLE_NAME}_nat; true"
    )
    out, code = run(cmd)
    append_log(paths.FIREWALL_LOG, f"flush rc={code} :: {out}")
    return {"ok": code == 0, "output": out}


def status() -> Dict:
    out_inet, code_inet = run(f"nft list table inet {TABLE_NAME}")
    out_nat, code_nat = run(f"nft list table ip {TABLE_NAME}_nat")
    return {
        "active": code_inet == 0 and code_nat == 0,
        "inet": out_inet if code_inet == 0 else "(missing)",
        "nat": out_nat if code_nat == 0 else "(missing)",
        "ruleset_path": paths.NFT_RULESET_PATH,
        "ruleset_present": os.path.exists(paths.NFT_RULESET_PATH),
    }


def reapply_from_state(
    wan_iface: Optional[str],
    ap_iface: Optional[str],
    lan_iface: Optional[str],
    mgmt_iface: Optional[str],
    api_port: int,
) -> Dict:
    ruleset = render_ruleset(wan_iface, ap_iface, lan_iface, mgmt_iface, api_port)
    return apply(ruleset)
