"""System-level helpers: Pi 5 detection, boot config tuning, zram, status."""

import os
import platform as py_platform
import re
import shutil
from datetime import datetime
from typing import Dict, List, Optional, Tuple

from .. import paths
from ..utils import read_text, run, run_ok


PI5_FAN_BLOCK = """# Added by RogueLink: Pi 5 Active Cooler thresholds
[all]
dtparam=fan_temp0=50
dtparam=fan_temp0_hyst=5
dtparam=fan_temp0_speed=75
dtparam=fan_temp1=60
dtparam=fan_temp1_hyst=5
dtparam=fan_temp1_speed=125
dtparam=fan_temp2=67
dtparam=fan_temp2_hyst=5
dtparam=fan_temp2_speed=192
dtparam=fan_temp3=75
dtparam=fan_temp3_hyst=5
dtparam=fan_temp3_speed=255
"""

PI5_PCIE_BLOCK = """# Added by RogueLink: PCIe Gen 3 for NVMe
[all]
dtparam=pciex1
dtparam=pciex1_gen=3
"""

PI5_OC_BLOCK = """# Added by RogueLink: light stability-first overclock
[all]
arm_freq=2600
over_voltage_delta=20000
"""

ZRAM_CONFIG = """# Generated by RogueLink
ALGO=zstd
PERCENT=50
SIZE=2048
PRIORITY=100
"""

ROGUELINK_BLOCK_MARKER = "# Added by RogueLink"


def _parse_os_release() -> Dict[str, str]:
    out: Dict[str, str] = {}
    text = read_text("/etc/os-release")
    for line in text.splitlines():
        if "=" not in line or line.startswith("#"):
            continue
        key, value = line.split("=", 1)
        out[key] = value.strip().strip('"').strip("'")
    return out


def detect_pi_model() -> str:
    model = read_text("/proc/device-tree/model")
    if model:
        return model
    text = read_text("/proc/cpuinfo")
    for line in text.splitlines():
        if line.lower().startswith("model"):
            return line.split(":", 1)[-1].strip()
    return ""


def is_pi5() -> bool:
    return "raspberry pi 5" in detect_pi_model().lower()


def is_raspberry_pi() -> bool:
    return "raspberry pi" in detect_pi_model().lower()


def detect_platform() -> Dict:
    osr = _parse_os_release()
    model = detect_pi_model()
    is_trixie = osr.get("VERSION_CODENAME", "").lower() == "trixie"
    return {
        "model": model or "Unknown / Generic Linux",
        "pretty_name": osr.get("PRETTY_NAME") or py_platform.platform(),
        "codename": osr.get("VERSION_CODENAME", "unknown"),
        "id": osr.get("ID", "unknown"),
        "kernel": py_platform.release(),
        "architecture": py_platform.machine(),
        "is_pi5": is_pi5(),
        "is_raspberry_pi": is_raspberry_pi(),
        "is_trixie": is_trixie,
    }


def boot_config_path() -> Optional[str]:
    for path in paths.BOOT_CONFIG_CANDIDATES:
        if os.path.exists(path):
            return path
    return None


def _backup(path: str) -> Optional[str]:
    if not os.path.exists(path):
        return None
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup = f"{path}.roguelink-bak-{stamp}"
    try:
        shutil.copy2(path, backup)
        return backup
    except OSError:
        return None


def _append_block_if_missing(path: str, block: str, sentinel: str) -> Tuple[bool, Optional[str]]:
    """Append `block` to `path` if `sentinel` is not already present.

    Returns (changed, backup_path).
    """
    text = read_text(path)
    if sentinel and sentinel in text:
        return False, None
    backup = _backup(path)
    try:
        with open(path, "a", encoding="utf-8") as f:
            if text and not text.endswith("\n"):
                f.write("\n")
            f.write(block)
            if not block.endswith("\n"):
                f.write("\n")
        return True, backup
    except OSError:
        return False, backup


def apply_pi5_boot_config() -> List[Dict]:
    """Apply Pi 5 fan, PCIe Gen 3, and light overclock blocks to config.txt."""
    results: List[Dict] = []
    path = boot_config_path()
    if not path:
        return [{"step": "boot_config", "ok": False, "detail": "config.txt not found"}]
    if not is_pi5():
        return [{"step": "boot_config", "ok": False, "detail": "not Raspberry Pi 5"}]

    for step, block, sentinel in (
        ("fan", PI5_FAN_BLOCK, "fan_temp0=50"),
        ("pcie", PI5_PCIE_BLOCK, "pciex1_gen=3"),
        ("overclock", PI5_OC_BLOCK, "arm_freq=2600"),
    ):
        changed, backup = _append_block_if_missing(path, block, sentinel)
        results.append(
            {
                "step": f"boot_config/{step}",
                "ok": True,
                "changed": changed,
                "backup": backup,
                "path": path,
            }
        )
    return results


def apply_zram() -> Dict:
    """Configure 2GB zram via /etc/default/zramswap if zram-tools is installed."""
    target = "/etc/default/zramswap"
    if shutil.which("apt-get") and not os.path.exists(target):
        run("DEBIAN_FRONTEND=noninteractive apt-get install -y zram-tools", timeout=180)
    backup = _backup(target) if os.path.exists(target) else None
    try:
        with open(target, "w", encoding="utf-8") as f:
            f.write(ZRAM_CONFIG)
    except OSError as exc:
        return {"step": "zram", "ok": False, "detail": str(exc), "backup": backup}
    run("systemctl restart zramswap.service", timeout=30)
    return {"step": "zram", "ok": True, "backup": backup}


def get_zram_status() -> str:
    swaps = read_text("/proc/swaps")
    zram_lines = [line for line in swaps.splitlines()[1:] if "zram" in line]
    if not zram_lines:
        return "Inactive / not detected"
    total_kb = 0
    for line in zram_lines:
        parts = line.split()
        if len(parts) >= 3 and parts[2].isdigit():
            total_kb += int(parts[2])
    total_mb = total_kb // 1024 if total_kb else 0
    return f"Active ({total_mb} MB across {len(zram_lines)} device(s))"


def get_temperature_c() -> Optional[float]:
    temps: List[float] = []
    for entry in sorted(os.listdir("/sys/class/thermal")) if os.path.isdir("/sys/class/thermal") else []:
        path = f"/sys/class/thermal/{entry}/temp"
        text = read_text(path)
        if not text:
            continue
        try:
            temps.append(int(text) / 1000.0)
        except ValueError:
            continue
    if temps:
        return max(temps)
    out, code = run("vcgencmd measure_temp")
    if code == 0:
        m = re.search(r"temp=([0-9.]+)", out)
        if m:
            try:
                return float(m.group(1))
            except ValueError:
                return None
    return None


def cpu_usage_percent() -> Optional[float]:
    """Snapshot CPU usage from /proc/stat (delta over a short interval)."""
    def snapshot():
        try:
            with open("/proc/stat", "r", encoding="utf-8") as f:
                line = f.readline().split()
        except OSError:
            return None
        if not line or line[0] != "cpu":
            return None
        nums = [int(v) for v in line[1:8]]
        idle = nums[3] + nums[4]
        total = sum(nums)
        return idle, total

    s1 = snapshot()
    if not s1:
        return None
    import time as _t

    _t.sleep(0.2)
    s2 = snapshot()
    if not s2:
        return None
    idle_d = s2[0] - s1[0]
    total_d = s2[1] - s1[1]
    if total_d <= 0:
        return None
    return round(100.0 * (1 - idle_d / total_d), 1)


def memory_usage() -> Dict:
    info: Dict[str, int] = {}
    text = read_text("/proc/meminfo")
    for line in text.splitlines():
        if ":" not in line:
            continue
        key, rest = line.split(":", 1)
        parts = rest.strip().split()
        if not parts:
            continue
        try:
            info[key] = int(parts[0])
        except ValueError:
            continue
    total_kb = info.get("MemTotal", 0)
    available_kb = info.get("MemAvailable", info.get("MemFree", 0))
    used_kb = max(total_kb - available_kb, 0)
    pct = round(used_kb / total_kb * 100, 1) if total_kb else 0.0
    return {
        "total_mb": total_kb // 1024,
        "used_mb": used_kb // 1024,
        "available_mb": available_kb // 1024,
        "percent": pct,
    }


def disk_usage(path: str = "/") -> Dict:
    try:
        usage = shutil.disk_usage(path)
    except OSError:
        return {"total_gb": 0, "used_gb": 0, "free_gb": 0, "percent": 0.0}
    pct = round(usage.used / usage.total * 100, 1) if usage.total else 0.0
    gb = 1024 ** 3
    return {
        "total_gb": round(usage.total / gb, 1),
        "used_gb": round(usage.used / gb, 1),
        "free_gb": round(usage.free / gb, 1),
        "percent": pct,
    }


def daemon_status() -> Dict:
    out, code = run("systemctl is-active roguelinkd.service")
    return {
        "active": code == 0 and out.strip() == "active",
        "raw": out.strip(),
    }


def overview() -> Dict:
    return {
        "platform": detect_platform(),
        "cpu_percent": cpu_usage_percent(),
        "memory": memory_usage(),
        "disk": disk_usage(),
        "temperature_c": get_temperature_c(),
        "zram": get_zram_status(),
        "daemon": daemon_status(),
    }


def reboot_required() -> bool:
    """Boot config changed since last boot but no reboot has happened yet."""
    path = boot_config_path()
    if not path:
        return False
    text = read_text(path)
    if ROGUELINK_BLOCK_MARKER not in text:
        return False
    try:
        boot_time = float(read_text("/proc/uptime").split()[0])
    except (ValueError, IndexError):
        return False
    try:
        mtime = os.path.getmtime(path)
    except OSError:
        return False
    import time as _t

    return mtime > (_t.time() - boot_time)
